### ISSUE TITLE
Implementacja modelu danych 

### ISSUE THREAD

**Issue by AsteRons** [komakow/SensorsProject#6]
Implementacja w Java

**Comment by AsteRons** [comment]
Jakie dane będziecie mi wysyłać do wizualizacji?

Wydaje mi się, że:
**- nr. urządzenia**
**- czas pomiaru**
 **- dane -**  ...
Jakie dane mi wysyłacie?
W jakim formacie i ile ich będzie?

**Comment by komakow** [comment]
Jakie dane i ile ich będzie - to dobre pytanie, ale jeszcze nie zdefiniowane. Wołam @278854 jako programiste i w tym przypadku architekta oprogramowania jakie ma zdanie na ten temat.

**Comment by 278854** [comment]
Z samego pica będzie ciężko o czas pomiaru:). Z pica prześle pomiar ADC (bez obróbki) do Rpi  + ewentualny nr. urządzenia. Tam można wykonać obliczenia, dodać datę i przepchnąć dalej. Format hmm JSON? Chyba że macie lepsze propozycje. Pomiar co 5 minut
